### ISSUE TITLE
Pairing Phrase not accepted when trying to connect with LNC

### ISSUE THREAD

**Issue by islandbitcoin** [ZeusLN/apollo#3]
![Screen Shot 2022-10-18 at 12 40 55 PM](https://user-images.githubusercontent.com/34528298/196492014-8be0b368-9b36-4678-bff4-a20e01ceec8c.png)

**Comment by islandbitcoin** [comment]
note, I'm running Lightning Terminal on my Start9 Embassy, and my LND v0.51.2 is running over Tor

**Comment by SpencerPearson** [comment]
I am having a similar issue, "rpc error: code = Unknown desc = lnd macaroon validation failed: rpc error: code = Unknown desc = permission denied" is the error message I get when first connecting and then I get the error @islandbitcoin screencapped on subsequent connection attempts.

I am running Lightning Terminal on a Raspiblitz, LND v 0.15.3 and hybrid mode via tunnelsats.

**Comment by kaloudis** [comment]
@SpencerPearson I believe you need to delete your LND macaroon and restart LND

**Comment by kaloudis** [comment]
@islandbitcoin I need a little more info. Could you share what's happening in your browser console?

**Comment by islandbitcoin** [comment]
> @islandbitcoin I need a little more info. Could you share what's happening in your browser console?

It worked the next time I tried it, maybe it was a caching issue, or maybe updating and restarting LND helped. 

either way I cannot reproduce, so this issue can be closed.
